### ISSUE TITLE
Used git submodules to include storage integrations

### ISSUE THREAD

**Issue by oparkins** [rgpm/core#18]
@irremotus What do you think of using git submodules to automatically include storage integrations? I believe that means that when you pull rgpm/core, it will pull the correct version of rgpm/storage_integrations.

Related to #4

**Comment by oparkins** [comment]
Some resources that I have been looking at:
- https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/
- https://medium.com/@porteneuve/mastering-git-submodules-34c65e940407


Both articles say to stay away from git submodules. Instead, use some package manager. GitHub is working on creating a package repository.... Maybe the timing will work out and we will be able to use GitHub as our package repository. Then we can use yarn/npm to manage dependencies

**Comment by irremotus** [comment]
From my experience trying to use git submodules, I completely agree.
