### ISSUE TITLE
Separated crypto classes for Node and browser JS

### ISSUE THREAD

**Issue by irremotus** [rgpm/core#9]
crypto for Node and for browser JS should be in separate classes so that they can be chosen once, rather than each time a method is called.  This also eliminates the "magic" method choosing.

**Comment by oparkins** [comment]
See commit 1203fa83dd9bb32d0c621b227f3f3d2098c30d71

**Comment by oparkins** [comment]
See commit 5565b423e8f93998e63edb9ffe56d26055d62c40

@irremotus I'm finishing the test classes, but I'm running into a road block about testing if the crypto method is not real. I haven't put too much thought into it, but at first looks it will be difficult to test that with how I have setup the code. There is now a factory method that will return the proper subclass of crypto. It will throw an error if a usable crypto class is not found, though I'm not sure how to test that. Any ideas?

**Comment by irremotus** [comment]
> See commit [5565b42](https://github.com/rgpm/core/commit/5565b423e8f93998e63edb9ffe56d26055d62c40)
> 
> @irremotus I'm finishing the test classes, but I'm running into a road block about testing if the crypto method is not real. I haven't put too much thought into it, but at first looks it will be difficult to test that with how I have setup the code. There is now a factory method that will return the proper subclass of crypto. It will throw an error if a usable crypto class is not found, though I'm not sure how to test that. Any ideas?

How to test that it will throw an error if no usable crypto class is found?  Or how to test that each crypto class is found correctly?

**Comment by oparkins** [comment]
I was thinking primarily about the first issue (no usable crypto is found)... But the other one is also something that would be worth testing if possible

**Comment by irremotus** [comment]
All that has to be done is to make the check fail... for example, for the check for WebCrypto, the test setup could temporarily set crypto.subtle to undefined.  This setup would need to include a portion for each crypto type, then all the types would fail, and trigger the error.
